### ISSUE TITLE
1038. Binary Search Tree to Greater Sum Tree

### ISSUE THREAD

**Issue by eeeesong** [huequad/swift-algorithm#1]
https://leetcode.com/problems/binary-search-tree-to-greater-sum-tree

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-07-05-1038.-Binary-Search-Tree-to-Greater-Sum-Tree/

**Comment by zeke-iOS** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/LeetCode/Leet-1038.swift

**Comment by lenaios** [comment]
https://github.com/lenaios/problem-solving/blob/main/DFS/BinarySearchTreeToGreaterSumTree.swift
