### ISSUE TITLE
43165. 타겟 넘버

### ISSUE THREAD

**Issue by lenaios** [huequad/swift-algorithm#2]
https://programmers.co.kr/learn/courses/30/lessons/43165

**Comment by lenaios** [comment]
https://github.com/lenaios/problem-solving/blob/main/DFS/43165_타겟넘버.swift

**Comment by zeke-iOS** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/Programmers/타겟%20넘버.swift

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-07-04-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4_%EA%B7%B8%EB%9E%98%ED%94%84%ED%83%90%EC%83%89_-%ED%83%80%EA%B2%9F%EB%84%98%EB%B2%84/
