### ISSUE TITLE
111. Minimum Depth of Binary Tree

### ISSUE THREAD

**Issue by zeke-iOS** [huequad/swift-algorithm#3]
https://leetcode.com/problems/minimum-depth-of-binary-tree/

**Comment by zeke-iOS** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/LeetCode/Leet-111.swift

**Comment by lenaios** [comment]
https://github.com/lenaios/problem-solving/blob/main/DFS/MinimumDepthOfBinaryTree.swift

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-07-01-LeetCode_111.-Minimum-Depth-of-Binary-Tree/
