### ISSUE TITLE
42888. 오픈채팅방

### ISSUE THREAD

**Issue by zekexros** [huequad/swift-algorithm#34]
https://programmers.co.kr/learn/courses/30/lessons/42888
카카오 대비용...?

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-09-09-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4_%EC%98%A4%ED%94%88%EC%B1%84%ED%8C%85%EB%B0%A9/

**Comment by zekexros** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/Programmers/오픈채팅방.swift

    Case
    enter: \(id)님이 들어왔습니다 -> 배열에 저장
    leave: \(id)님이 나갔습니다 -> 배열에 저장
    change: dict[id] = nick -> dict타입 업데이트

    배열에 저장된 요소들의 id에 nickName삽입

    끝

**Comment by lenaios** [comment]
https://gist.github.com/lenaios/ccc875c53b172f907ee915b37d1f8f95

**Comment by eeeesong** [comment]
https://github.com/eeeesong/algorithm/blob/master/프로그래머스/42888.md
