### ISSUE TITLE
72410. 신규 아이디 추천

### ISSUE THREAD

**Issue by ghis22130** [huequad/swift-algorithm#35]
https://programmers.co.kr/learn/courses/30/lessons/72410

저도 그럼 카카오 준비겸.. 긴 지문에 당황하지 말고 명세를 잘 정리하자!

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-09-10-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4_%EC%8B%A0%EA%B7%9C-%EC%95%84%EC%9D%B4%EB%94%94-%EC%B6%94%EC%B2%9C/

**Comment by zekexros** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/Programmers/신규%20아이디%20추천.swift

**Comment by lenaios** [comment]
https://github.com/lenaios/problem-solving/blob/main/String/72410.swift

**Comment by eeeesong** [comment]
https://github.com/eeeesong/algorithm/blob/master/프로그래머스/72410.md
