### ISSUE TITLE
72412. 순위검색

### ISSUE THREAD

**Issue by ghis22130** [huequad/swift-algorithm#37]
캌아오 지옥..
https://programmers.co.kr/learn/courses/30/lessons/72412

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-09-15-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4_%EC%88%9C%EC%9C%84%EA%B2%80%EC%83%89/

와 왜이렇게 어렵냐 ㅜ

**Comment by zekexros** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/Programmers/순위%20검색.swift

**Comment by eeeesong** [comment]
https://github.com/eeeesong/algorithm/blob/master/프로그래머스/72412.md

아 빡세네

**Comment by lenaios** [comment]
https://github.com/lenaios/problem-solving/blob/main/Binary%20Search/72412.md
