### ISSUE TITLE
60057. 문자열 압축

### ISSUE THREAD

**Issue by lenaios** [huequad/swift-algorithm#39]
https://programmers.co.kr/learn/courses/30/lessons/60057

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-09-16-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4_%EB%AC%B8%EC%9E%90%EC%97%B4-%EC%95%95%EC%B6%95/

**Comment by eeeesong** [comment]
https://github.com/eeeesong/algorithm/blob/master/프로그래머스/60057.md

이것도 문제 이해가 좀,,,

**Comment by zekexros** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/Programmers/문자열%20압축.swift
문자열 자르기 이후에 압축부분에서 안풀려 어떤 블로그를 적극 참고하였습니다😢

**Comment by lenaios** [comment]
https://github.com/lenaios/problem-solving/blob/main/String/60057.md
