### ISSUE TITLE
226. Invert Binary Tree

### ISSUE THREAD

**Issue by zeke-iOS** [huequad/swift-algorithm#4]
https://leetcode.com/problems/invert-binary-tree/

**Comment by zeke-iOS** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/LeetCode/Leet-226.swift

**Comment by eeeesong** [comment]
https://github.com/eeeesong/algorithm/blob/master/LeetCode/0226.md

**Comment by lenaios** [comment]
https://github.com/lenaios/problem-solving/blob/main/DFS/InvertBinaryTree.swift

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-07-03-LeetCode_226-Invert-Binary-Tree/
