### ISSUE TITLE
42746. 가장 큰 수

### ISSUE THREAD

**Issue by eeeesong** [huequad/swift-algorithm#44]
https://programmers.co.kr/learn/courses/30/lessons/42746

**Comment by zekexros** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/Programmers/가장%20큰%20수.swift

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-10-04-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4_%EA%B0%80%EC%9E%A5%ED%81%B0%EC%88%98/

**Comment by lenaios** [comment]
https://github.com/lenaios/problem-solving/blob/main/Sort/42746.md
