### ISSUE TITLE
81301. 숫자 문자열과 영단어

### ISSUE THREAD

**Issue by zekexros** [huequad/swift-algorithm#47]
https://programmers.co.kr/learn/courses/30/lessons/81301

**Comment by zekexros** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/Programmers/숫자%20문자열과%20영단어.swift

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-10-08-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4_%EC%88%AB%EC%9E%90-%EB%AC%B8%EC%9E%90%EC%97%B4%EA%B3%BC-%EC%98%81%EB%8B%A8%EC%96%B4/

**Comment by lenaios** [comment]
https://github.com/lenaios/problem-solving/blob/main/Hash/81301.swift

**Comment by eeeesong** [comment]
https://github.com/eeeesong/algorithm/blob/master/프로그래머스/81301.md
