### ISSUE TITLE
17680. 캐시

### ISSUE THREAD

**Issue by eeeesong** [huequad/swift-algorithm#48]
https://programmers.co.kr/learn/courses/30/lessons/17680

**Comment by zekexros** [comment]
https://github.com/zeke-iOS/AlgorithmPractice/blob/main/Programmers/캐시.swift

**Comment by ghis22130** [comment]
https://ghis22130.github.io/2021-10-10-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4_%EC%BA%90%EC%8B%9C/

**Comment by lenaios** [comment]
https://github.com/lenaios/problem-solving/blob/main/StackQueue/17680.md

**Comment by eeeesong** [comment]
https://github.com/eeeesong/algorithm/blob/master/프로그래머스/17680.md
